create table if not exists users(
    id bigint generated by default as identity primary key,
    telegram_id bigint not null unique,
    username varchar(100),
    created_at timestamp default now()
);

create table if not exists media (
    id bigint generated by default as identity primary key,
    source_url text not null,
    external_id text not null unique,
    title varchar(255) not null,
    year int not null check (year > 1900),
    poster_url text not null,
    updated_at timestamp default now()
);

create table if not exists watch_entries(
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    media_id bigint not null references media(id),
    status text not null,
    status_changed_at timestamp not null,
    unique (user_id, media_id)
);

create table if not exists reviews(
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    media_id bigint not null references media(id),
    rating int not null check (rating >= 0 and rating <= 5),
    review_text text
);

create table if not exists persons(
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null,
    external_id text not null,
    birthdate date not null,
    profession text
);

create table if not exists media_person_roles(
        id bigint generated by default as identity primary key,
        user_id bigint not null references users(id),
        media_id bigint not null references media(id),
        role_type varchar(255),
        character_name varchar(255) not null
);