telegram.bot.token=pupu
telegram.bot.username=MediaTrackerItparkMvpBot

kinopoisk.base-url=https://kinopoiskapiunofficial.tech
kinopoisk.api-key=pupu

db.url=jdbc:postgresql://localhost:5432/media_tracker
db.username=media_tracker
db.password=media_tracker

hibernate.show-sql=true
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update