telegram.bot.token=8793078626:AAH3Am26HnWNXugocqA8a4wYGxYyGNCBRIY
telegram.bot.username=mediatrackeritparkbot

kinopoisk.base-url=https://kinopoiskapiunofficial.tech/
kinopoisk.api-key=8478f4ef-2d5b-46a5-bceb-429272ebc525

db.url=jdbc:postgresql://localhost:5432/media_tracker
db.username=media_tracker
db.password=media_tracker

hibernate.show-sql=true
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update